### ISSUE TITLE
[Feature] Denote AVR only for Microcontroller entry

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_toolbox#101]
We should change th eUI so that it denotes that the MCU dropdown is for AVR only. 

## Feature Request Type

- [x] New behavior

**Comment by fauxpark** [comment]
I tried appending the text "AVR only" to the label, but it doesn't really fit. I think a decent solution could be only enable the dropdown when a bootloader that requires an MCU parameter to be flashed is detected.

**Comment by skullydazed** [comment]
Personally I'd like to see the dropdown go away and detect the MCU based on USB id. We did [this in the old qmk flasher](https://github.com/qmk/qmk_flasher/blob/master/src/MainWindow/app.js#L15) and it seemed to work well.

**Comment by fauxpark** [comment]
For DFU that is easy, as each MCU has its own PID. But the Toolbox also supports flashing with AVRISP/USBAsp/USBTiny, which have only a single PID as you're not connecting to the MCU directly.

**Comment by skullydazed** [comment]
Would it make sense for the dropdown to be disabled (and maybe blank) unless that PID is detected?

**Comment by fauxpark** [comment]
That's what I was getting at. If we find a bootloader that requires avrdude/teensyloader and *isn't* Caterina (I think that is 32U4 only?), the MCU must be manually chosen. Otherwise, we can deduce it from the AVR DFU VID/PID, or ignore it for ARM.

**Comment by drashna** [comment]
I think this has been mostly resolved, or at least is handled better now.
