### ISSUE TITLE
No option for STM32 microcontroller

### ISSUE THREAD

**Issue by MarcosBottenbley** [qmk/qmk_toolbox#108]
## Bug Description
When I plug my keyboard and qmk toolbox detects the keyboard it doesn't include an option for STM32 in the microcontroller section. So since I have a preonic rev3 I can't flash on windows using this tool.

## System Information

 - Operating system: Windows 10
 - QMK Toolbox version: 0.0.11

**Comment by drashna** [comment]
You don't need to select a controller for the ARM based boards.  You only need to do so for the AVR boards.

So you should be able to just flash it, even if the controller isn't set correctly.
