### ISSUE TITLE
version 0.0.12 still contains 0.0.11 as short version string

### ISSUE THREAD

**Issue by suschizu** [qmk/qmk_toolbox#112]
hello! I've noticed that the latest release still contains 0.0.11 as version
<img width="298" alt="Screenshot 2019-08-30 at 21 12 00" src="https://user-images.githubusercontent.com/16004333/64046069-2ee1cd00-cb6b-11e9-8b14-ff05d8678601.png">

**Comment by drashna** [comment]
Yeah, it's an issue with how it was compiled.  It didn't clean up stuff properly and kept the old version. :(

**Comment by suschizu** [comment]
thanks for the info!

**Comment by drashna** [comment]
Well, fixed, by upgrading to 0.0.13, at least. And verified that it should be numbered correctly this time!

**Comment by suschizu** [comment]
Great! thank you :)
