### ISSUE TITLE
christmas_tree .hex file url throws 404 error

### ISSUE THREAD

**Issue by jsank** [qmk/qmk_toolbox#12]
noticed that when trying to pull the .hex file inside QMK Toolbox it throws the 404 error.

it should be  trying to get this: http://qmk.fm/compiled/christmas_tree_V2017_default.hex

except in the software it does not have the "V2017" version.

we were not sure why this happened.

thanks!

**Comment by mavanmanen** [comment]
Compiled file might have been unavailable at the time, seems like it is available right now.

**Comment by jackhumbert** [comment]
Looks like this was fixed in https://github.com/qmk/qmk_firmware/pull/2160 - thanks!
