### ISSUE TITLE
Allow custom programming executables

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_toolbox#123]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

With dfu-util, the current release version doesn't support STM32L412 devices, as there's a timing change with the way that chip does DFU.

The master branch of dfu-util has a fix for this, but unfortunately nobody knows when a new release build will get made, given that the last one was in 2016.

Would be great if there could be an option to specify alternate executables when invoking things like dfu-util and avrdude etc. -- would allow for custom builds to be run locally without requiring a full release.

**Comment by skullydazed** [comment]
Good idea!

The mechanism for this should probably be environment variables. Something like this set:

* `DFU_UTIL=dfu-util`
* `DFU_PROGRAMMER=dfu-programmer`
* `TEENSYLOADER=teensyloader`
