### ISSUE TITLE
Preonic Rev3 default Keymap file extension incorrect

### ISSUE THREAD

**Issue by RustyJonez** [qmk/qmk_toolbox#126]
## Describe the Bug
When downloading a copy of the default keymap for a Rev3 Preonic, the url points to an incorrect file extension.

Currently:

https://qmk.fm/compiled/preonic_rev3_default.hex

Should be:

https://qmk.fm/compiled/preonic_rev3_default.bin

## System Information

 - Operating system: Win 7 64bit
 - QMK Toolbox version: 11

**Comment by drashna** [comment]
I thought I had an issue open for this already, but this is a known issue. 

@fauxpark any ideas?

**Comment by fauxpark** [comment]
Well, there is https://github.com/qmk/qmk_toolbox/issues/62.

I don't know if there is a way to download the file with the correct extension short of using the API.

**Comment by RustyJonez** [comment]
FWIW, the .bin file can still be downloaded in a web browser and loaded into Toolbox as a workaround for the time being.

**Comment by fauxpark** [comment]
I thought of a very simple, but rather ugly, hack:
![Screen Shot 2019-11-11 at 1 05 31 pm](https://user-images.githubusercontent.com/4781841/68555964-5bc43180-0484-11ea-9b7d-d5da2cab1704.png)
![Screen Shot 2019-11-11 at 1 05 05 pm](https://user-images.githubusercontent.com/4781841/68555966-5e268b80-0484-11ea-9144-89e23dfcb5fe.png)

It might be acceptable until the new API can provide this information, there is no ETA on that. I'll see if I can do the same for Windows.
