### ISSUE TITLE
Crash on MacOS Mojave while trying to flash

### ISSUE THREAD

**Issue by clbx** [qmk/qmk_toolbox#152]
## Describe the Bug

QMK Toolbox Crashes when trying to flash Massdrop Alt board

## System Information

 - Operating system: MacOS 10.14.6 Mojave
 - QMK Toolbox version: 0.0.15 (1)

## Additional Context

On flashing (Both Massdrop Default and my own FW) QMK Immediately Crashes. The Problem holds [this](https://pastebin.com/s89JQzUp). However this seems like the most important part

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
abort() called
terminating with uncaught exception of type NSException
```

Seems like its looking to some part of the program and it either can't find it or can't execute it.

## What I've tried so far

I've given ``avrdude dfu-programer dfu-util teensy_loader_cli`` execute permissions, I'm not sure which one QMK uses for the Alt, but this didn't seen to fix the issue.

**Comment by fauxpark** [comment]
Sorry about that! Yeah, we had a similar problem with dfu-util not having the executable bit set in Git, which propagated out to the final build artifact, so the Toolbox couldn't run it. Seems like this is the same issue but with the Massdrop Loader tool. The PR linked above will fix it, but it may be a short while before there's a new release. For now, you can just `chmod +x mdloader_mac` in the QMK Toolbox.app.

**Comment by clbx** [comment]
Giving execute permissions to the mdloader did not fix the issue.

**Comment by clbx** [comment]
@fauxpark @drashna setting the executable bit still crashes the program.

**Comment by fauxpark** [comment]
Ah, I see what the problem is now. The link to it in the Xcode project was set up incorrectly. This time you'll have to wait for a new release, sorry :/
