### ISSUE TITLE
Update release documentation to warn about false malware alarms

### ISSUE THREAD

**Issue by toindev** [qmk/qmk_toolbox#158]
Hello,

Several engines flag the latest release as malware: https://www.virustotal.com/gui/file/8502264a2fa69fa08f359d8d44c0e15f14a98aaaf5056977e6c20cf3f1fdeb8d/detection

(Note: Virustotal will only flag when scanning the file, but not the URL, strangely, which scared me into thinking I had some exe-modifying malware on my machine).

To avoid scaring other users as I've been, it could be interesting to document the security software warnings, detecting the toolbox as a riskware (https://www.kaspersky.com/blog/not-a-virus/18015/).

Regards,

**Comment by fauxpark** [comment]
Thanks, I've updated the release notes for 0.0.15.
