### ISSUE TITLE
Autoflash is dangerous

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_toolbox#18]
Since this is happened REPEATEDLY to me....  (You'd think I'd learn, but here we are)...

Would it be possible to "lock down" the autoflash to  single device (as an option), or enable "only if mod/shift/key is held down" option?
This would prevent idiots like me from flashing the wrong firmware on their boards (and potentially bricking the controller)

**Comment by skullydazed** [comment]
Just thinking aloud here, what if Autoflash turned off after a timeout? Say 1 hour after the last flash?

**Comment by drashna** [comment]
That would work too.

**Comment by mavanmanen** [comment]
Maybe turn off if there hasn't been a flash for more than like 10 minutes?

**Comment by jackhumbert** [comment]
It might not hurt to have a separate "Flash when ready" checkbox that deactivates once it flashes, like a one-shot.

**Comment by mavanmanen** [comment]
Should be closed, fixed in #24
