### ISSUE TITLE
XD75 Mac QMK toolbox dfu-programmer: no device present.

### ISSUE THREAD

**Issue by rendomnet** [qmk/qmk_toolbox#194]
Trying to flash using QMK.

I have put my keyboard to reset mode.

It shows DFU device connected but then when I click flash. it gives me "dfu-programmer: no device present."
![image](https://user-images.githubusercontent.com/18900210/81495571-00f48100-92d3-11ea-9692-2454b3f7bcba.png)

**Comment by fauxpark** [comment]
Have you tried updating the Toolbox?

**Comment by rendomnet** [comment]
@fauxpark version 0.0.17 (1). Downloaded from here https://github.com/qmk/qmk_toolbox/releases

**Comment by fauxpark** [comment]
Do you see anything in System Information, under USB? Also, what version of macOS are you running?

**Comment by rendomnet** [comment]
@fauxpark  Mojave 10.14.6
![image](https://user-images.githubusercontent.com/18900210/81501263-475cd680-92f9-11ea-80be-947dd5755860.png)

**Comment by fauxpark** [comment]
Okay, what about when it's running as a keyboard?

**Comment by rendomnet** [comment]
@fauxpark same. 
But under Windows10 I see new device. But also cant flash.

**Comment by fauxpark** [comment]
This isn't a hackintosh build, is it?

**Comment by rendomnet** [comment]
@fauxpark it is.

**Comment by rendomnet** [comment]
Under Windows same thing. 
![image](https://user-images.githubusercontent.com/18900210/81501933-c1428f00-92fc-11ea-91ad-3bfddc46415c.png)

**Comment by fauxpark** [comment]
In that case, I guess there is some problem with the USB kext or something, not the Toolbox - I'm not really familiar with Hackintosh stuff, but the complete lack of USB devices at all made me suspicious. With absolutely nothing connected to my MBP I still see two internal hub devices:
![image](https://user-images.githubusercontent.com/4781841/81501876-f27f8700-931d-11ea-9a33-c0b5366d5d9c.png)

As for the Windows side, you'll probably need to install the drivers. On first run the Toolbox should prompt you to install them, and if that doesn't work run [Zadig](https://zadig.akeo.ie) and make sure the ATm32U4DFU device (the bootloader of your XD75) has the libusb0/libusb-win32 driver (not WinUSB or libusbK)

**Comment by rendomnet** [comment]
@fauxpark yeah I have tried Zadig and for some reason when I'm pressing install after several seconds it just closes. :-|

**Comment by fauxpark** [comment]
Tried running as admin? Anything in Event Viewer?

**Comment by rendomnet** [comment]
@fauxpark yeah running as administrator 
![image](https://user-images.githubusercontent.com/18900210/81503299-aecc5380-9304-11ea-8449-acb0cd8d05d6.png)

**Comment by fauxpark** [comment]
`tumint.dll` seems to be part of some software called GammaTech TumarCSP, I'm not sure what that is. Looks Russian and shady.

**Comment by rendomnet** [comment]
@fauxpark hurray! Uninstalling this software helped!

**Comment by fauxpark** [comment]
@rendomnet can this be closed?
