### ISSUE TITLE
Error while writing

### ISSUE THREAD

**Issue by amowry** [qmk/qmk_toolbox#199]
I've heard from someone using the most recent QMK Toolbox release for Mac who had an error while writing to a 32u4 that appears to have bricked the device. I was just wondering if you have seen this before? It appears to have been writing and then encountered an error. Thanks!
<img width="632" alt="Screenshot 2020-05-23 at 13 20 47" src="https://user-images.githubusercontent.com/14002160/82733691-6a5c9280-9cca-11ea-961a-fe63d276f6f9.png">

**Comment by fauxpark** [comment]
Make sure you're on the latest version of macOS (there was a previous version of Catalina that avrdude had issues with when talking to the Pro Micro bootloaders; see https://github.com/qmk/qmk_firmware/issues/6133)
Also double check your connections and soldering, just in case the flakiness is coming from there.

If all else fails, you may have to ISP flash the chip: https://docs.qmk.fm/#/isp_flashing_guide

**Comment by amowry** [comment]
Okay, thanks for the suggestions!

**Comment by fauxpark** [comment]
@amowry any update on this? Did you get it working?

**Comment by amowry** [comment]
Thanks for checking in. I believe my customer ended up getting the installation to work on Windows instead, so we never figured out the Mac issue, but it's certainly possible it was user error. I've had a few hundred customers using QMK to update firmware on my device and it seems to work fine for most. Thanks very much for the support!
