### ISSUE TITLE
Unable to open app on Mac OS Big Sur

### ISSUE THREAD

**Issue by timtraversy** [qmk/qmk_toolbox#201]
##  Describe the Bug

I'm running the beta of Mac OS Big Sur. I installed the latest release of `QMK.Toolbox.app.zip`,  currently `0.0.18`, and I'm unable to run it. There's a bunch of apps that are broken on Big Sur right now, so I assume some arch change was made that's causing this issue.

https://forums.macrumors.com/threads/big-sur-working-not-working-apps.2242312/

## System Information

 - Operating system: Mac OS Big Sur
 - QMK Toolbox version: 0.0.18

**Comment by skullydazed** [comment]
Can you provide detail on what happens when you try to run it? Is there a crash report you can attach?

**Comment by timtraversy** [comment]
If I open it from Dock it fails quietly, if I open it from Spotlight I get a `Impossible to open application "QMK Toolbox"`

**Comment by timtraversy** [comment]
The only error it's reporting is `No architectures specified in launch archictectures [ NULL ]  for app=file:///Applications/QMK%20Toolbox.app/ which likely is an error.`, so that could be it

**Comment by timtraversy** [comment]
But actually, I'm seeing that in the logs for other apps that are launching fine.

**Comment by timtraversy** [comment]
Dropbox is failing also, and their log included `ImportError: Framework CoreServices could not be found`

https://www.dropboxforum.com/t5/Dropbox-files-folders/Dropbox-app-doesn-t-start-on-MacOS-Big-Sur-11-0-beta/td-p/431820

**Comment by skullydazed** [comment]
Interesting, thanks for the information. One last test, if you find `QMK Toolbox.app` in the Finder, right click it, and select "Open", does that change the behavior?

**Comment by timtraversy** [comment]
No, still fails to open that way.

Another thing, from system.log:

```
```

**Comment by skullydazed** [comment]
Does it fail silently like the dock, or with a message like spotlight?

**Comment by timtraversy** [comment]
It fails silently.

**Comment by skullydazed** [comment]
Thanks! I don't know when someone will have time to install the beta and look at this further, but for now we'll leave this open. Anyone who is interested in the state of QMK Toolbox on Big Sur can subscribe to this issue for updates.

**Comment by nooges** [comment]
I’ll have the beta installed soon enough to do some investigation.

**Comment by ehagerty** [comment]
run it as sudo /Applications/QMK\ Toolbox.app/Contents/MacOS/QMK\ Toolbox

i've seen a lot of apps need this in the past year as a beta tester

**Comment by timtraversy** [comment]
That did it for me, thanks @ehagerty! I think we should keep this open until it can be resolved without the command line.

**Comment by fauxpark** [comment]
I'm running Big Sur now (11.0.1), and it seems to work just fine as is. I tested flashing a couple of devices and that appears to work too. @timtraversy @ehagerty can you confirm?

**Comment by ehagerty** [comment]
@fauxpark thank you very much!

MacBook Pro (15-inch, 2019)
macOS 11.0.1 (20B29)
QMK Toolbox 0.0.20 (1)

Runs as expected, without needing sudo as above.

**Comment by fauxpark** [comment]
Closing, Toolbox appears to be running fine on Big Sur so far.
