### ISSUE TITLE
New Release to Fix Major Memory Flashing Bug

### ISSUE THREAD

**Issue by ennation** [qmk/qmk_toolbox#217]
#215 was pulled a couple weeks ago to fix #189, however a new release has not been pushed for those who are experiencing the issue. Luckily, I was able to clone the repo and build the toolbox from source to fix the issue for myself when I experienced it. Alternatively, using the QMK CLI with the --force flag would work as well.

However, I am worried for the many less-experienced users of QMK who may just wish to flash their keymap from config.qmk.fm, run into the rather large issue mentioned earlier, and might freak out when their brand new keyboard seems to be bricked. Many such users may find building apps from source, or using the CLI, quite daunting of tasks, and thus I believe a new release version should be pushed out for a) the support of these users, and b) the convenience of everyone else.

**Comment by fauxpark** [comment]
We generally only create a new Toolbox release when there are sufficient new improvements (preferably on both macOS and Windows) to warrant one. In the meantime, you can download the CI artifacts from the Actions tab if you want to be on the "bleeding edge".
