### ISSUE TITLE
Auto-Flash to Elite-C not working on Mac OSX Catalina

### ISSUE THREAD

**Issue by bilzard** [qmk/qmk_toolbox#256]
## Describe the Bug

Auto-flash functionality didn't worked when writing firmware to [Elite-C](https://deskthority.net/wiki/Elite-C).

## System Information

 - Operating system: Mac OSX Catalina (10.15.7)
 - QMK Toolbox version: 0.0.21

## Additional Context

If I check Auto-Flash, qmk toolbox's console outputs `There are no devices available`, and failed to write firmware (fig1). 
However, manually pushing flash button worked (fig2).
The issue didn't reproduce in version 0.0.20 (fig3).

fig1. checked Auto-Flash on ver. 0.0.21
<img width="670" alt="スクリーンショット 2021-04-11 23 04 29" src="https://user-images.githubusercontent.com/36561962/114311290-27e1b580-9b29-11eb-9bbc-8edfa425c107.png">

fig2. manually push flash button on ver. 0.0.21
<img width="669" alt="スクリーンショット 2021-04-11 23 05 38" src="https://user-images.githubusercontent.com/36561962/114311444-c0783580-9b29-11eb-8a75-94f89e9e6344.png">

fig3. checked Auto-Flash on ver. 0.0.20
<img width="668" alt="スクリーンショット 2021-04-12 0 48 19" src="https://user-images.githubusercontent.com/36561962/114311313-37f99500-9b29-11eb-9f45-6fc711498aba.png">

**Comment by fauxpark** [comment]
Thanks, this should be fixed in the above linked PR :)
