### ISSUE TITLE
When ever i plug my board in doesn't detect my device in dfu mode past version 0.0.18

### ISSUE THREAD

**Issue by Colepng** [qmk/qmk_toolbox#266]
## System Information

 - Operating system: windows 10 
 - QMK Toolbox version: 0.0.18 and aboce

## Additional Context

I'm also having trouble using 0.0.18 to flash my board when every it tries it says

>>> dfu-programmer.exe atmega32u4 erase --force

dfu-programmer: no device present.

>>> dfu-programmer.exe atmega32u4 flash "C:\Users\gamin\Documents\Keyboard stuff\DZ60 rgb rev 2\Firmware\dztech_dz60rgb_ansi_v2_my_frist_keyboard.hex"

dfu-programmer: no device present.
![Screenshot (2)](https://user-images.githubusercontent.com/85180852/123169519-62c86980-d447-11eb-901b-8b166b74372f.png)
![Screenshot (1)](https://user-images.githubusercontent.com/85180852/123169536-6825b400-d447-11eb-86e8-bb978ac78efb.png)

>>> dfu-programmer.exe atmega32u4 reset

dfu-programmer: no device present.
 
windows and qmk 0.0.18 both decect my device in dfu but they say its a Atmel Corp. USB Mass Storage Device (03EB:2045:0001)

**Comment by fauxpark** [comment]
The Toolbox doesn't support this new Mass Storage bootloader used on KBDfans boards (and never did, more recent versions simply are more specific about which devices it detects, previously it just looked for the Atmel VID of 03EB).

You have to replace the FLASH.BIN file on the drive - note that it must be a .bin file, the .hex file won't work.
