### ISSUE TITLE
libftdi1.dll missing

### ISSUE THREAD

**Issue by kylemccreery** [qmk/qmk_toolbox#294]
## Describe the Bug

Flashing to caterina bootloaders using 0.1.0 on windows is failing due to libftdi1.dll missing. This was tested and replicated by several others before posting.

## System Information

 - Operating system: Windows 10
 - QMK Toolbox version: 0.1.0

## Additional Context

Note: Flashing using dfu-util works as expected. This seems to be specific to avrdude.

On first run, we were all prompted to install drivers (as expected). This seems to complete with no errors. I ran it again manually to verify and again it completed fine.

Worth noting that both the standalone .exe and full installer were used to test and are resulting in the same error.

![image](https://user-images.githubusercontent.com/26013377/127786493-5921503c-843e-4e10-9b94-4a97e21dbda5.png)

**Comment by daskygit** [comment]
Seems like the avrdude bundled with MSYS requires [mingw-w64-x86_64-libftdi](https://packages.msys2.org/package/mingw-w64-x86_64-libftdi?repo=mingw64)

You can place the dll in `%LOCALAPPDATA%\QMK\QMK Toolbox\0.1.0` and avrdude will work correctly. (assuming you installed toolbox). If you have QMK MSYS installed you can grab the dll from `C:\QMK_MSYS\mingw64\bin\libftdi1.dll`

I've just confirmed it works over here, had to flash caterina to a promicro 👎
