### ISSUE TITLE
Finish adding SparkFun device support

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_toolbox#3]
https://github.com/qmk/qmk_toolbox/blob/5495a01a5d07539931ce1cb11b08b05deec40bae/windows/QMK%20Toolbox/Form1.cs#L376

You added the VID, but no check for it.  

However, I can confirm that adding ` || caterina_alt_vid.Success` to the caterina line does fix the issue, and allow the device to be flashed.

**Comment by jackhumbert** [comment]
Thanks for confirming! I need to add it to the OSX version as well :)

**Comment by jackhumbert** [comment]
This will be in 0.0.9 :)
