### ISSUE TITLE
QMK Toobox flash success but UT47.2 isn't working

### ISSUE THREAD

**Issue by dangvanthanh** [qmk/qmk_toolbox#307]
## Describe the Bug

QMK Toobox flash success but UT47.2 isn't working

## System Information

 - Operating system:  Windows 10
 - QMK Toolbox version:  0.1.1

## Additional Context

![ut47 2](https://user-images.githubusercontent.com/2674850/136034409-abc64389-44fa-4d34-8f43-3b7f862688e6.jpg)

**Comment by fauxpark** [comment]
https://docs.qmk.fm/#/driver_installation_zadig?id=recovering-from-installation-to-wrong-device

**Comment by dangvanthanh** [comment]
@fauxpark 

Thank you very much. After try use qmk command line for reflash. I found I use wrong hex for my UT47.2.

I configuration other hex and it is working.
