### ISSUE TITLE
qmk toolbox does not open

### ISSUE THREAD

**Issue by nysterix** [qmk/qmk_toolbox#310]
I have been using QMK toolbox fine for several days on Windows 10 but today, it looks like it just doesn't want to work. 
I've uninstalled and reinstalled several times. I see it running (32bit) on task manager and I can alt+tab and see it running but it never fully displays or fully loads up.

**Comment by daskygit** [comment]
Does it open if you unplug any keyboards you have connected?

**Comment by nysterix** [comment]
ooop, yeah I really should learn how to fully read other threads first.... disconnecting all flashed keyboards and reconnecting fixed it. ty

**Comment by PotatoJet** [comment]
Stupid guy,use vpn,and you will open it！
