### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by rampantx** [qmk/qmk_toolbox#315]
I'm trying to flash my kbd6x but I've been running into some problems. I've installed and uninstalled drivers and tried other .hex files but I can't get it to work. I can't type anything with it as all the keys are not responsive but from what I can tell the fn keys are working since I can change the RGB functions.

**Comment by sigprof** [comment]
If RGB control works, but no keypresses are actually seen on the computer, most likely you have some wrong drivers installed; you will need to fix that as described in the [Recovering from Installation to Wrong Device](https://docs.qmk.fm/#/driver_installation_zadig?id=recovering-from-installation-to-wrong-device) section of the documentation. Note that you may need to uninstall drivers for seemingly the same device multiple times until they are finally gone.
