### ISSUE TITLE
Toolbox does not let me press the flash button

### ISSUE THREAD

**Issue by emilioxmedina** [qmk/qmk_toolbox#323]
The aplication does not let me press the flash button I don´t know why or what to do
![imagen_2022-01-10_163041](https://user-images.githubusercontent.com/61241178/148849257-86792649-2666-4b5f-99c7-ee5bd285266e.png)

**Comment by fauxpark** [comment]
You need to put the board into bootloader mode first.

**Comment by emilioxmedina** [comment]
I have done it,but it won't work. I've watch videos were the button is active even when they haven't connected the keyboard so I don't understand why I can't use it.

**Comment by gety9** [comment]
@emilioxmedina where you able to solve the issue?
i have same - flash button is grey, even though i reset the keyboard.
