### ISSUE TITLE
Is Linux version just a draft?

### ISSUE THREAD

**Issue by ulgens** [qmk/qmk_toolbox#34]
I tried to compile and run `linux` folder but i see nothing but empty screen with buttons.

![image](https://user-images.githubusercontent.com/166637/37597203-c1f55b3e-2b8f-11e8-9c69-66688708333a.png)

Also, the folder itself looks like has no functional code except UI.

**Comment by skullydazed** [comment]
Sorry about the delay responding here, currently Linux is not supported. That's some GUI framework code that @jackhumbert has been playing around with in order to support Linux in the future.

**Comment by ulgens** [comment]
Thanks :disappointed:

**Comment by mollat** [comment]
Please write into the readme - so nobody else wastes time on it...

**Comment by paines** [comment]
Please, reopen this ticket. The linux version is just a dumb placeholder. The buttons do nothing at all.
