### ISSUE TITLE
Error on download

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_toolbox#37]
When attempting to download firmware, it errors out and produces this error: 
https://imgur.com/FndboIu

Looks like it's trying to grab "http://qmk.fm/compiled/", but the site wants to redirect to "https://qmk.fm/compiled/" automatically, and causing this issue.

**Comment by arrigobWSP** [comment]
Yeah, I am getting the same. Have you found a workaround yet by chance?

**Comment by ValeryIvanov** [comment]
Could this be released?

**Comment by drashna** [comment]
(fixed)
