### ISSUE TITLE
"Only firmware files in .bin format can be flashed with dfu-util" error

### ISSUE THREAD

**Issue by Tony-Sol** [qmk/qmk_toolbox#372]
I tried to flash geekboards macropad v2 with .hex file from https://github.com/arduxio/qmk-ardux via QMK Toolbox which is recommended to, and got an error:
```
Only firmware files in .bin format can be flashed with dfu-util
```
But it seems that hex files should be supported by Toolbox

System: macos Monterey 12.3.1
QMK Toolbox version: 0.2.2 (installed via brew)

**Comment by fauxpark** [comment]
`geekboards/macropad_2` is an STM32F072 board.
https://github.com/qmk/qmk_firmware/tree/master/keyboards/geekboards/macropad_v2
If you're getting a hex file, you are not compiling the right board.
