### ISSUE TITLE
Qmk Toolbox unable to open uf2 files

### ISSUE THREAD

**Issue by dissmaterial** [qmk/qmk_toolbox#386]
I have been trying to flash an STM32 using the newest version of qmktoolbox 0.2.2. I have been able to successfully connect the bootloaded STM32, however qmk toolbox does not let me open uf2 files - even though it is stated to be supported. Instead it will only allow me to open .bin or .hex files

I compiled the firmware using the qmk configurator - so I'm confused as to why they do not seem compatible

help would be much appreciated

**Comment by keyboard-magpie** [comment]
If you truly have an stm32 that takes UF2 it should present as a mass storage device that you can drag and drop UF2 files into, without requiring Toolbox.

**Comment by fauxpark** [comment]
The Toolbox does not support UF2 files. I'm not sure where you saw that.

**Comment by dissmaterial** [comment]
ahh - all working now - thanks for the point in the right direction!:
