### ISSUE TITLE
Virus Total hits

### ISSUE THREAD

**Issue by williamdean19** [qmk/qmk_toolbox#391]
Getting the four warnings on virustotal for the windows installer .exe file:

I saw another issue about the code not being signed. I would like to see this signed to feel safer about using it.
You can close this issue if it's too related to the other one.

Thanks,
Will

CrowdStrike Falcon
Win/grayware_confidence_70% (D)

Cynet
Malicious (score: 100)

Tencent
Trojan.Win32.Offloader.zk

Trapmine
Suspicious.low.ml.score

![image](https://user-images.githubusercontent.com/17956781/205516079-7e9267ed-e9ad-4c16-9916-9f26d41e4bc5.png)

From the Behavior tab (wondering what's up with the IP traffic?)
![image](https://user-images.githubusercontent.com/17956781/205516257-c1f57780-37bf-4021-af44-79d65db45dda.png)

![image](https://user-images.githubusercontent.com/17956781/205516301-5b1bbaba-0102-4483-a3ff-c525e6c72d13.png)

**Comment by keyboard-magpie** [comment]
These are expected hits when using this software. 

Signing is happening, review the current PRs.

**Comment by tzarc** [comment]
![image](https://user-images.githubusercontent.com/2985843/205518719-2a9f8ba6-9caa-4e22-bc41-a1b4cc54dfa4.png)

Signed build.

**Comment by williamdean19** [comment]
Thanks for the follow up! Sorry if I missed a posted update. Thanks,
Will
