### ISSUE TITLE
Won't let me press the flash button

### ISSUE THREAD

**Issue by emilioxmedina** [qmk/qmk_toolbox#402]
I bought the already welded PCB from little keyboards, got my .HEX file ready but tha app won't let me use the flash button. Please help me.

![imagen](https://user-images.githubusercontent.com/61241178/216087637-059209a4-6047-42df-b98b-55db312afdaa.jpg)

**Comment by fauxpark** [comment]
https://docs.qmk.fm/#/newbs_flashing
