### ISSUE TITLE
Keyboard freezing after 5 press of the lighting mode switch

### ISSUE THREAD

**Issue by duckyz1** [qmk/qmk_toolbox#403]
## System Information

 - Operating system: 
 Windows 10 Pro 21H2 19044.2486
 
 - QMK Toolbox version: 
0.2.2
## Additional Context

Attempting to flash, please don't remove device
> dfu-programmer.exe atmega32u4 erase --force
> Erasing flash...  Success
> Checking memory from 0x0 to 0x6FFF...  Not blank at 0x1.
> dfu-programmer.exe atmega32u4 flash --force "C:\Users\DuckyZ1\Downloads\mwstudio_mw75_default.hex"
> 0%                            100%  Programming 0x6A00 bytes...
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
> 0%                            100%  Reading 0x7000 bytes...
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
> Validating...  ERROR
> 27018 invalid bytes in program region, 1530 outside region.
> FAIL
> Memory did not validate. Did you erase?
> dfu-programmer.exe atmega32u4 reset
Flash complete
Atmel DFU device disconnected (libusb0): Atmel Corp. ATmega32U4 (03EB:2FF4:0000)

**Comment by duckyz1** [comment]
Im like almost sure this is a corrupted chip of somesort. I can't isp flash I don't have any experience of doing so. I also can't buy. are there any ways on how I can fix this using software???

**Comment by keyboard-magpie** [comment]
No. 

I agree this looks like bootloader corruption. The only way to fix this is with an external ISP flasher. This can be something as simple as a pro micro.

**Comment by tzdhbo21** [comment]
> Im like almost sure this is a corrupted chip of somesort. I can't isp flash I don't have any experience of doing so. I also can't buy. are there any ways on how I can fix this using software???

Follow up pls. Mine meets the similar issue. Cannot read Cannot flash

**Comment by duckyz1** [comment]
bump, any fix? my keyboard has been stuck with no lighting I kind've miss the lights.

**Comment by tzarc** [comment]
The “fix” has been described — use ISP flashing to reinstall the bootloader.

**Comment by keyboard-magpie** [comment]
Fix was stated above. If you're having issues come and discuss on the discord server. Otherwise, refer to https://docs.qmk.fm/#/isp_flashing_guide?id=isp-flashing-guide
