### ISSUE TITLE
GMMK2 96% not recognized in DFU mode by QMK Toolbox in OSX Ventura

### ISSUE THREAD

**Issue by xanothos** [qmk/qmk_toolbox#410]
OSX Ventura 13.3.1 on 2018 MacBook Air Intel i5
GMMK2 Ansi 96% Keyboard
QMK Toolbox 0.2.2

<img width="800" alt="Screenshot 2023-05-31 at 07 18 37" src="https://github.com/qmk/qmk_toolbox/assets/172064/d69fff6e-f941-4aea-af60-4dd7430974cd">

**Comment by fauxpark** [comment]
Current release does not support WB32.
