### ISSUE TITLE
 keyboard doesnt work after flash 

### ISSUE THREAD

**Issue by jaekim24** [qmk/qmk_toolbox#414]
I have a DZ60 pcb board and after I flashed it with my .hex file the keyboard doesnt type. For some reason the backspace is now tab some how. Is my keyboard fried? 
![Capture](https://github.com/qmk/qmk_toolbox/assets/62858192/97415731-5a59-4671-b532-57e386bccd34)

**Comment by fauxpark** [comment]
Not a toolbox issue.
