### ISSUE TITLE
read write eeprom atmega32u4

### ISSUE THREAD

**Issue by ulao** [qmk/qmk_toolbox#418]
Is there anyway to read or write to eeprom with this tool?

chip atmegas32u4
using the basic driver

I can manfully read and write eeprom but only if I first erase the chip.

to read 

dfu-programmer atmega32u4 erase
dfu-programmer atmega32u4 read --force  --eeprom  >test2.eep

to write

dfu-programmer atmega32u4 flash --force  --eeprom  "test2.eep"

but this is strange to me, why erase first, that defeatists the point of eeprom. Without an erase I get errors, I was oping this app new a way around this. but I see no read write eeprom options.

**Comment by fauxpark** [comment]
The factory bootloader from Atmel requires a full chip erase before you can write anything. There is no workaround other than using a different bootloader.
