### ISSUE TITLE
Request for new official release

### ISSUE THREAD

**Issue by tkchris93** [qmk/qmk_toolbox#43]
I am running into an issue on the latest official release that was later fixed in #22. I don't know how to build the code from source on Windows, so I would really appreciate a new official release. Thanks!

**Comment by eturior** [comment]
Same here

**Comment by kavu** [comment]
@jackhumbert Hi, Jack! Can you give an estimate on this? Thanks!

**Comment by takashiski** [comment]
@jackhumbert We cannot load even default keymaps from qmk.fm by toolbox, but I think it resolve #38. We need new release ASAP.

**Comment by amatecha** [comment]
On that note, the Mac download link is no longer working (as of this moment).  Guess I'll try v0.0.8…

**Comment by kevinduffey** [comment]
Doesnt seem the link works @coarse? Just gives me empty page. I am still having the same Toolbox issue that was shown last year.. e.g. plugging in an IRIS keyboard controller (trying to flash them) doesnt work. I am hoping I followed the chatter on that issue that got me here and that this is resolved/fixed and hopefully a new toolbox for windows is available to use?

**Comment by drashna** [comment]
I've also updated the exe in the 0.9 release with the most recent version.

**Comment by Durnlaw** [comment]
I am having the same error from [#17](https://github.com/qmk/qmk_toolbox/issues/17). Which I think is in line with what others are saying on this thread? Sorry, new to this.

**Comment by dmcgits** [comment]
I'm looking for the BootloadHID support too :D 
Weirdly there's BootloadHID support in Drashna's exe, I can load the jj50 firmware, but I can't see any way to connect to a v-usb device

**Comment by drashna** [comment]
Well, I'm working on this. I finally figured out how to make the installer, actually.  

Only issue is that I don't have any Apple devices, and no way to compile it for MacOS :(

**Comment by drashna** [comment]
New release added.  Grab 0.0.10
