### ISSUE TITLE
"Unhandled exception has occurred in your application." 

### ISSUE THREAD

**Issue by AwakeJJ** [qmk/qmk_toolbox#430]
Hello I've been having this issue with this popup 
![image](https://github.com/qmk/qmk_toolbox/assets/150179564/4875c37f-d98d-460d-99d2-458fc61c45f1) 
 
If you're interested in the details i put it in a txt file
[Microsoft NET.txt](https://github.com/qmk/qmk_toolbox/files/13284561/Microsoft.NET.txt)

Im getting the same thing when i try to look at my HID console
![image](https://github.com/qmk/qmk_toolbox/assets/150179564/720ec40e-3f36-40ca-84d0-6d0cc140db26)

and here is that ones txt file
[QMK tool.txt](https://github.com/qmk/qmk_toolbox/files/13284586/QMK.tool.txt)

running it as admin and reinstalling drivers did nothing for me and now I'm just trying to fix my stuff

Also it isnt detecting my KB 
OS: Window 11
KB: KBD67 REV2

**Comment by fauxpark** [comment]
Please paste the details here.

**Comment by AwakeJJ** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

 Exception Text 
System.Runtime.InteropServices.COMException (0x80040154) Class not registered

   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementEventWatcher.Initialize()
   at System.Management.ManagementEventWatcher.Start()
   at QMK_Toolbox.HidConsole.HidConsoleListener.Start()
   at QMK_Toolbox.HidConsole.HidConsoleWindow.HidConsoleWindow_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


 Loaded Assemblies 
System.Private.CoreLib
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
qmk_toolbox
    Assembly Version 0.2.2.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Threading
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Collections
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Windows.Forms
    Assembly Version 6.0.2.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version 6.0.2.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Drawing.Primitives
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Collections.Specialized
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.ObjectModel
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Drawing.Common
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Threading.Thread
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
Accessibility
    Assembly Version 4.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.ComponentModel
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Numerics.Vectors
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Memory
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Collections.Concurrent
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Linq
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Private.Uri
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Diagnostics.Process
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Private.Xml
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Net.WebClient
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime.Loader
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Resources.Extensions
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Drawing
    Assembly Version 6.0.2.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Reflection.Emit
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version 1.0.0.0
    Win32 Version na
    CodeBase fileCProgram%20FilesQMK%20ToolboxSystem.Private.Xml.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Management
    Assembly Version 7.0.0.2
    Win32 Version na
    CodeBase 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Reflection.Metadata
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Collections.Immutable
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.IO.Compression
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
HidLibrary
    Assembly Version 3.2.49.0
    Win32 Version na
    CodeBase fileCProgram%20FilesQMK%20ToolboxSystem.Private.CoreLib.dll
----------------------------------------
netstandard
    Assembly Version 2.1.0.0
    Win32 Version na
    CodeBase 
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version 6.0.0.0
    Win32 Version na
    CodeBase 
----------------------------------------

 JIT Debugging

**Comment by fauxpark** [comment]
This is an issue with your Windows install, not the Toolbox.
