### ISSUE TITLE
Arduino Leonardo not detected

### ISSUE THREAD

**Issue by shini199** [qmk/qmk_toolbox#431]
my Arduino Leonardo board is not detected im using version [0.2.2]

![Screenshot 2023-11-11 170741](https://github.com/qmk/qmk_toolbox/assets/64566022/3e4de9ee-73be-4dcc-92e7-19c1f382ed1a)

**Comment by fauxpark** [comment]
You need to put it into bootloader mode.

**Comment by shini199** [comment]
how do i put it in bootloaded mode

**Comment by fauxpark** [comment]
GitHub issues is not really the place for this kind of support. You can find that information easily on Google.
