### ISSUE TITLE
[HELP] Keychron Q3 Lightning didn't works

### ISSUE THREAD

**Issue by hryer** [qmk/qmk_toolbox#441]
Hello, I apologize if this isn't the right place to raise an issue.

I'm having trouble with my Keychron Q3 QMK Custom Mechanical Keyboard's lighting. It's currently not working. When I checked VIA, I encountered several errors, as shown in the pictures below. I'm seeking guidance on how to resolve this issue. Is a factory reset of my keyboard necessary? While the keys themselves function perfectly, the lighting isn't turning on at all.

![image](https://github.com/qmk/qmk_toolbox/assets/12638095/8ff17b2e-b420-4bd7-9a96-fbe1481a2d5e)
![image](https://github.com/qmk/qmk_toolbox/assets/12638095/8c9bc02e-486c-4846-b0d4-e7efd2fb9e52)

**Comment by keyboard-magpie** [comment]
This should be taken up with the via team on their discord server: https://discord.gg/4fMw7YkDfY

**Comment by hryer** [comment]
okay, thank you for the information
