### ISSUE TITLE
After flashing a KBD KeyPad MK3 the device is not showing up anymore

### ISSUE THREAD

**Issue by Slurbisaur** [qmk/qmk_toolbox#458]
I used the QMK config online and baked my Firmware, even checked the Json and it seems fine to me. 

downloaded the .hex file and flashed it for ATmega32U2 which is stated on the boards controller. 
seems to flash fine no errors, but after it says finished and disconnected no buttons work of that keypad. 
Tried the pad on several PC's

any ideas ?

**Comment by tzarc** [comment]
`kbdfans/kbdpad/rev3` is a ATmega32U4. You've said your chip is a 32U2, so you've either got a new revision QMK doesn't know about, or you don't have a kbdpad. Your next step is to get in touch with kbdfans' support as there's nothing QMK can do without knowing what board it actually is.

**Comment by Slurbisaur** [comment]
Oh I checked the board again and it says MKII rev. 1.3 sorry for the slip up but I assumed it has to be MKIII because the QMK configurator shows the MKII as having 2x "0" keys
