### ISSUE TITLE
Error when flashing kb

### ISSUE THREAD

**Issue by Leandroqo** [qmk/qmk_toolbox#462]
## Describe the Bug
I'm encountering an error when attempting to flash my crkbd. Any ideas on how to resolve it?

* QMK Toolbox 0.3.1 (https://qmk.fm/toolbox)
* Supported bootloaders:
*  - ARM DFU (APM32, Kiibohd, STM32, STM32duino) and RISC-V DFU (GD32V) via dfu-util (http://dfu-util.sourceforge.net/)
*  - Atmel/LUFA/QMK DFU via dfu-programmer (http://dfu-programmer.github.io/)
*  - Atmel SAM-BA (Massdrop) via Massdrop Loader (https://github.com/massdrop/mdloader)
*  - BootloadHID (Atmel, PS2AVRGB) via bootloadHID (https://www.obdev.at/products/vusb/bootloadhid.html)
*  - Caterina (Arduino, Pro Micro) via avrdude (http://nongnu.org/avrdude/)
*  - HalfKay (Teensy, Ergodox EZ) via Teensy Loader (https://pjrc.com/teensy/loader_cli.html)
*  - LUFA/QMK HID via hid_bootloader_cli (https://github.com/abcminiuser/lufa)
*  - WB32 DFU via wb32-dfu-updater_cli (https://github.com/WestberryTech/wb32-dfu-updater)
*  - LUFA Mass Storage
* Supported ISP flashers:
*  - AVRISP (Arduino ISP)
*  - USBasp (AVR ISP)
*  - USBTiny (AVR Pocket)
* Auto-Flash enabled
Caterina device connected: Arduino LLC Arduino Leonardo (2341:0036:0001) [/dev/cu.usbmodem1101]
Attempting to flash, please don't remove device
> avrdude -p atmega32u4 -c avr109 -U flash:w:/Users/leandro.queiroz/qmk_firmware/crkbd_rev1_leandroqo.hex:i -P /dev/cu.usbmodem1101 -C avrdude.conf
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:399]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:400]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:428]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:429]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:461]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:462]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:495]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:496]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:522]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:523]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:563]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:564]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:583]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:584]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:602]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:603]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:648]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:649]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:732]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:734]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:743]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:745]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:755]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:757]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:768]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:770]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:791]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:793]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:815]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:817]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1184]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1185]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1195]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1197]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1218]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1219]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1236]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1237]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1252]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1253]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1263]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1264]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1274]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1275]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1285]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1286]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1302]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1306]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1319]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1320]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1330]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1331]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1341]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1342]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1351]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1353]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1375]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1376]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1430]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1431]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1452]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1453]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1466]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1467]
> avrdude warning: mosi is deprecated, will be removed in v8.0, use sdo [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1480]
> avrdude warning: miso is deprecated, will be removed in v8.0, use sdi [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1481]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:1694]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:3178]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:3361]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:3541]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:3733]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:3925]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:4118]
Flash complete
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:4321]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:4529]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:4737]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:4931]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:5123]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:5479]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:5661]
> avrdude warning: ATmega329's flash writepage misses a necessary address bit a13 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:5780]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:5887]
> avrdude warning: ATmega649's flash writepage misses a necessary address bit a14 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:6006]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:6086]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:7042]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:7233]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:7424]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:7674]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:7886]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:8098]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:8312]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:8500]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:8718]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:8907]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9091]
> avrdude warning: AT90PWM2's eeprom writepage misses a necessary address bit a8 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9169]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9374]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9558]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9741]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:9927]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:10117]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:10320]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:10762]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:10946]
> avrdude warning: ATtiny44's eeprom writepage misses a necessary address bit a7 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11027]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11130]
> avrdude warning: ATtiny84's eeprom writepage misses a necessary address bit a8 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11211]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11315]
> avrdude warning: a4 would normally be expected to be a5 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: a3 would normally be expected to be a4 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: a2 would normally be expected to be a3 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: a1 would normally be expected to be a2 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: a0 would normally be expected to be a1 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: too few opcode bits in instruction [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11374]
> avrdude warning: ATtiny43u's eeprom read misses a necessary address bit a5 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11393]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11496]
> avrdude warning: ATmega32U4's eeprom writepage misses a necessary address bit a2 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11579]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11687]
> avrdude warning: ATmega16U4's eeprom writepage misses a necessary address bit a2 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11770]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:11878]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12082]
> avrdude warning: AT90USB1286's eeprom writepage misses a necessary address bit a11 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12165]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12284]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12285]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12471]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12472]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12660]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12661]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12848]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:12849]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13036]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13037]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13219]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13410]
> avrdude warning: has_pdi is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13624]
> avrdude warning: avr_mem_order[] does not know data; add to array and recompile
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13752]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13841]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:13941]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14094]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14152]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14264]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14396]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14496]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14773]
> avrdude warning: is_avr32 is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14774]
> avrdude warning: has_debugwire is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14798]
> avrdude warning: ATtiny1634's flash writepage misses a necessary address bit a5 [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14921]
> avrdude warning: has_tpi is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:14987]
> avrdude warning: has_jtag is deprecated, will be removed in v8.0, use prog_modes [/Applications/QMK Toolbox.app/Contents/Resources/avrdude.conf:15110]
> avrdude warning: System wide configuration file version ()
>         does not match Avrdude build version (7.3)
> avrdude error: cannot find programmer id avr109
> use -c? to see all possible programmers
Caterina device disconnected: Arduino LLC Arduino Leonardo (2341:0036:0001) [/dev/cu.usbmodem1101]

## System Information

 - Operating system: MacOS Sonoma 14.4 M1
 - QMK Toolbox version: 0.3.1

## Additional Context

➜ qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.5
Ψ QMK home: /Users/leandro.queiroz/qmk_firmware
Ψ Detected macOS 14.4 (Apple Silicon).
Ψ Git branch: master
Ψ Repo version: 0.12.47
⚠ Git has unstashed/uncommitted changes.
Ψ - Latest master: 2023-11-06 23:07:44 -0300 (a66312332c) -- crkbd leandroqo based on gotham
Ψ - Latest upstream/master: 2024-03-13 08:24:21 +0100 (aa73362674) -- [Keyboard] add glyphkbd_v2 (#23131)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2023-08-15 19:06:18 +1000 (dbd847d4d3) -- [Keyboard] Add Chouchou keyboard (#21699)
Ψ - Common ancestor with upstream/develop: None
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 13.2.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.3-2024022
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-04-15 13:48:04 +0000 --  (11edb1610)
Ψ - lib/chibios-contrib: 2023-01-11 16:42:27 +0100 --  (a224be15)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found

**Comment by right7ctrl** [comment]
I just faced the same issue on my M1. Using version 0.2.2 its worked for me

**Comment by Leandroqo** [comment]
> I just faced the same issue on my M1. Using version 0.2.2 its worked for me

It's worked. Thanks 🤘

**Comment by izaakm** [comment]
I'm also having this issue w/ v0.3.1.

I propose re-opening this because downgrading it does not resolve the issue.
