### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by kylehovey** [qmk/qmk_toolbox#54]
Here is what I see when I get the error:
![image](https://user-images.githubusercontent.com/7339800/47270121-2de01800-d524-11e8-9719-d6317832c942.png)

**Comment by skullydazed** [comment]
Unfortunately we don't have anything to do with qmkeyboard.cn, we can't help you with that. If your keyboard has support in qmk_firmware already you can try our GUI:

https://config.qmk.fm/

**Comment by kylehovey** [comment]
Whoops, I blindly clicked the github link and opened an issue assuming this was their repo... Sorry about that. Thanks for the great config utility!
