### ISSUE TITLE
Reset EEPROM doesn't work for atmega32u2

### ISSUE THREAD

**Issue by colemarkham** [qmk/qmk_toolbox#56]
Clicking the "Reset EEPROM" runs `dfu-programmer atmega32u2 erase --force` with a message that prints 'success'. There is no indication that the EEPROM was not actually reset. To support atmega32u2, the empty EEPROM file just needs to be added to the build alongside the 32u4 file, but any other processor that doesn't work should print a message.

**Comment by fauxpark** [comment]
It seems like `atmega32u4_eeprom_reset.hex` only erases the first 128 bytes. Evidently QMK currently doesn't use more than that.

Considering all supported MCUs have far more than 128 bytes of EEPROM, I don't think we need an extra hex file - the existing one can probably serve as a generic EEPROM clearer for AVRs.

**Comment by drashna** [comment]
@fauxpark all we need to do is wipe the first byte of EEPROM, actually.  If that's cleared, it's not `FEED` (aka the magic number for eeprom), and will trigger an initialization on the next startup of the firmware.  

Honestly, I think it would be better to include an eep file, and flash that instead. That would be more "compatible" anyways.

**Comment by fauxpark** [comment]
Something like this then:

```
:0100000000FF
:00000001FF
```
