### ISSUE TITLE
Latest Windows release flagged as TROJAN

### ISSUE THREAD

**Issue by wywywywy** [qmk/qmk_toolbox#57]
I don't know if it is a known issue, but the latest qmk_toolbox.exe on the release page is flagged as Trojan:Win32/Occamy.C by Windows Defender on Windows 10.

**Comment by drashna** [comment]
This should be resolved now, I think.

**Comment by corrigat** [comment]
Malwarebytes is also currently flagging blootloadHID.exe as Spyware.PasswordStealer

**Comment by drashna** [comment]
This should be resolved now.

**Comment by nxion** [comment]
I recently downloaded v 0.0.10 and Windows Defender still marks it as a virus. It says it is Win32/Occamy.C

Here is a screenshot of it [https://imgur.com/a/qZpmGy3](Imgur of error)
