### ISSUE TITLE
Error flashing pro micro on windows

### ISSUE THREAD

**Issue by Micro-Biology** [qmk/qmk_toolbox#60]
Issue occurs whilst using qmk toolbox on windows 8.1 enterprise edition.

Possibly related to [this issue #42](https://github.com/qmk/qmk_toolbox/issues/42).

`avrdude.exe -p atmega32u4 -c avr109 -U flash:w:"<hex-file-location>\macro12_default.hex":i -P 
    <qmk-install-location>\QMK\QMK Toolbox\0.0.9\avrdude.exe: option requires an argument -- P
    Usage: avrdude.exe [options]`

I assume it its just a error and it should be this or something similar:
`avrdude.exe -p atmega32u4 -c avr109 -U flash:w:"<hex-file-location>\macro12_default.hex":i -P "<qmk-install-location>\QMK\QMK Toolbox\0.0.9\avrdude.exe"`

**Comment by gwerbin** [comment]
Same error, looks like some things got mixed up in the most recent release.

**Comment by Micro-Biology** [comment]
Does anyone know how to use an older version? (or a new version with this fixed?)

**Comment by Telchii** [comment]
I was experiencing the same issue tonight. After making sure QMK Toolbox was up to date, I did some googling and found an [/r/MechanicalKeyboards thread](https://www.reddit.com/r/MechanicalKeyboards/comments/9tzh89/helpflashing_pro_micro/) from November 2018, with the following recommendations:

1. Install the Arduino IDE software package: https://www.arduino.cc/en/Main/Software (Try this one first and make sure you're not trying to start a flash after the device disconnects.)

2. Run the qmk_driver_installer. Download the zip, extract it and run the "install_all_drivers" script. https://github.com/qmk/qmk_driver_installer/releases

After installing both of these, I was able to flash my pro micro. If you have auto-flash enabled, make sure it's set before you plug in any USB devices. I did have short the reset (RST) and ground (GND) pins a couple times (due to the small window to start the flash and auto flash not picking up my pro micro) and manually click Flash before the device disconnected.

**Comment by gwerbin** [comment]
@Micro-Biology download it from the Releases page in this repository.

**Comment by BramVer** [comment]
@drashna Updated the .exe in the latest release as said [here](https://github.com/qmk/qmk_toolbox/issues/43#issuecomment-442972731)

**Comment by Micro-Biology** [comment]
> I've also updated the exe in the 0.9 release with the most recent version.

Unfortunately I'm already on this release, I did try reinstalling, still has the bug.
I think its just missing some quotations for the install location, my coding is very limited (especially on windows) or I'd attempt to fix it myself.

**Comment by BramVer** [comment]
The same problem here, couldn't get any release to work anymore, both on a win 8.1 VM or a win 8.1 dedicated machine.  
I know a buddy with a Macbook and that one works fine though.

**Comment by drashna** [comment]
on a newly downloaded version, does this still happen? 
(eg, redownload 0.0.9)

**Comment by kncarrier28** [comment]
I just downloaded and get the same error. It's saying that the -P flag is given with no arguments. This flag is supposed to have the serial port for the device, so I'd guess that issue is with pulling in that serial port.

**Comment by drashna** [comment]
This may be fixed now?

**Comment by whitehot6er** [comment]
I just downloaded v 0.0.14 on Win 10 yesterday (11/22/19) and encountered the same problem. Using version 0.0.13 I was able to successfully flash my pro micro.

**Comment by yanfali** [comment]
> I just downloaded v 0.0.14 on Win 10 yesterday (11/22/19) and encountered the same problem. Using version 0.0.13 I was able to successfully flash my pro micro.

If you've upgraded windows recently it may have uninstalled the drivers. They do this on every major upgrade. Try reinstalling using zadig.

**Comment by fauxpark** [comment]
Zadig won't help, Caterina is driverless.

I don't see any changes between 0.0.13 and 0.0.14 that would affect the behaviour of avrdude (barely anything on the Windows side of things was touched). It is probably just a coincidence that downgrading worked - this particular error seems to be somewhat of a race condition related to the appearance of the COM port and the USB device providing it.

**Comment by fauxpark** [comment]
So as it turns out, there *was* a change that affected avrdude (more specifically, the COM port detection) after all. My bad. The PR linked above will fix this; for now just use the previous version.

**Comment by louia** [comment]
Not fixed for me, it just doesnt work with pro micro and QMK Toolbox 0.0.21 and avrdude 6..3

**Comment by fauxpark** [comment]
Could you post a screenshot?

**Comment by louia** [comment]
Yes, absolutly. My pro Micro is new, its the first time with QMK.

![image](https://user-images.githubusercontent.com/33846211/116215777-4611fd00-a748-11eb-94f1-8610311c62e8.png)

**Comment by fauxpark** [comment]
Have a look in Device Manager (hit `View->Devices by container`, and `Show hidden devices`). Uninstall any devices under the COM12 device, and tick the "uninstall driver" checkbox if there is one. Then try again.

**Comment by marcoklein** [comment]
Got the exact same error. Same versions as @louia - works if i execute the command manually and append `com7` in my case for the port:

`avrdude.exe -p atmega32u4 -c avr109 -U flash:w:"C:\Users\Marco\Documents\GitHub\qmk_firmware\crkbd_rev1_legacy_default.hex":i -P com7`

(Note the com7 after the -P)

![image](https://user-images.githubusercontent.com/15013357/118877718-0ecde080-b8ef-11eb-8ee7-b68f41f48234.png)

Error:
![image](https://user-images.githubusercontent.com/15013357/118877498-ce6e6280-b8ee-11eb-8cc7-cc05d716a49e.png)

**Comment by St3v3n-4n4** [comment]
se ha solucionado el error?
