### ISSUE TITLE
Block .hex uploads when using dfu-util

### ISSUE THREAD

**Issue by pelrun** [qmk/qmk_toolbox#63]
Dfu-util doesn't support ihex formatted files, but it will happily open them and send them as raw data... which obviously doesn't work.

Have Toolbox detect such attempts and stop with an error explaining that the .bin version needs to be used instead.

**Comment by drashna** [comment]
Well, that should be fixed on the back end now.

Specifically, we should be pushing BIN files to qmk.fm, which is where the toolbox grabs the firmware images from. 
Now, we just need to figure out how to grab them, when appropriate.

**Comment by pelrun** [comment]
Fixing the backend ensures that the downloader doesn't provide a bogus file, but it doesn't help when people use Toolbox to flash their own binaries, or ones they downloaded manually. Which is what happens for a large proportion of people we've been helping on Discord with this problem.

Toolbox shouldn't be letting you flash garbage to a kb (at least, when it's easily detected.) Ideally the dfu-util devs would pull their heads out and add that check themselves, but I don't see that happening any time soon.
