### ISSUE TITLE
Upon installing the install package in windows, a way for the libusb0 driver to be automatically installed

### ISSUE THREAD

**Issue by TurboMech** [qmk/qmk_toolbox#7]
I've seen this quite a lot.  People can't figure out how to install the driver, if the windows install package installed the driver(s) automatically this would save a lot time and issues.

**Comment by jackhumbert** [comment]
Yeah! This is fixed at HEAD - will be included in the 0.0.9 release :)

**Comment by TurboMech** [comment]
@jackhumbert awesome! Feel free to close this issue whenever you want then! You da bomb!
