### ISSUE TITLE
Add ability to delete entries in file list for MacOS side 

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_toolbox#77]
## Feature Request Type

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

This feature does/will exist for the Windows side, but not the macOS side. So to keep feature parity, it would need to be added on the MacOS side.

**Comment by fauxpark** [comment]
It's seeming non-trivial to add a keyDown event handler to the combobox in a similar way to how #68 does it, so I'm still in favour of having a proper Open Recent menu for both.

**Comment by fauxpark** [comment]
Well, macOS doesn't "do" hover selections for combobox dropdowns, apparently. But otherwise I've got it working.

**Comment by fauxpark** [comment]
The combo box is populated through the recent documents list managed by NSDocumentController, which doesn't provide any way to remove specific entries from the list...so this wouldn't be persistent.

I *could* get it to send `clearRecentDocuments:` when the number of items reaches zero...but...egh.

**Comment by nooges** [comment]
Random thought that's a hack: call `clearRecentDocuments:` then repopulate with `noteNewRecentDocumentURL:` with deleted item excluded.
