### ISSUE TITLE
Spaces in paths cause file loading to fail (macOS)

### ISSUE THREAD

**Issue by WillEccles** [qmk/qmk_toolbox#87]
## Describe the Bug

On macOS Mojave, loading a .hex file with a space in the path results in a path with a %20 in it, which is presumably the error. The file just won't load. However, when the file is moved to a path without a space, there are no problems. If this is macOS specific, I would potentially say that there's a misuse of string/path handling utilities in Obj-C, but since I haven't use it in a while and don't have the time to look into this myself right now, that's the most I can say.

## System Information

 - Operating system: macOS Mojave
 - QMK Toolbox version: 0.0.10

**Comment by drashna** [comment]
Windows have the same issue, IIRC. 

So, yeah, we should/need to do some parsing of the path string to fix this.

**Comment by fauxpark** [comment]
I can confirm this is a macOS-only problem, which I've fixed in the PR above.

**Comment by WillEccles** [comment]
Just had time to look at @fauxpark's changes. Looks like potentially the simplest fix I've ever seen to something, but it's about what I was expecting given the nature of Obj-C. 10/10.

**Comment by WillEccles** [comment]
Updated title to reflect the nature of the bug.
