### ISSUE TITLE
Windows Toolbox crashes with "Unhandled Exception" if DFU driver is missing

### ISSUE THREAD

**Issue by nooges** [qmk/qmk_toolbox#92]
## Describe the Bug

If the bootloader driver is missing for some MCUs, QMK Toolbox crashes.

## System Information

 - Operating system: Windows
 - QMK Toolbox version: 

## TODO:

Handle the exception and prompt user to install DFU driver for the board using Zadig.

**Comment by drashna** [comment]
Better would be if we force installed the correct driver, at that point.  Which is possible, IIRC.  I think that Wally 1.0.1 is doing that.

**Comment by fauxpark** [comment]
Duplicate of #61

**Comment by drashna** [comment]
This still happening?
