### ISSUE TITLE
v 0.0.10 Windows release flagged as TROJAN

### ISSUE THREAD

**Issue by halogenica** [qmk/qmk_toolbox#96]
This is a continuation of issue https://github.com/qmk/qmk_toolbox/issues/57

Release v 0.0.10 of qmk_toolbox.exe and qmk_toolbox_install.exe is flagged as Trojan:Win32/Occamy.C by Windows Defender on Windows 10.

A screenshot of the issue (courtesy of @nxion): https://imgur.com/a/qZpmGy3

**Comment by fauxpark** [comment]
Already resolved by https://github.com/qmk/qmk_toolbox/pull/89 it appears, just waiting on a new release.

**Comment by halogenica** [comment]
Closed because this was a duplicate, thanks @fauxpark!
